# Generated by Django 4.1.1 on 2023-01-19 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollsquestions',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
